# Generated by Django 5.2.2 on 2026-06-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['geocoded', 'latitude', 'longitude'], name='api_fuelsta_geocode_d9a994_idx'),
        ),
    ]
